-- Build script for bluloco.nvim
--
-- Generates static theme files from the lush spec so that lush is not needed at runtime.
-- Run from the plugin directory:
--
--   nvim --headless -c "luafile build.lua" -c "qa"
--
-- Requires lush.nvim to be installed (only needed for building, not at runtime).

local plugin_dir = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":h")
local theme_dir = plugin_dir .. "/lua/bluloco/theme"

--- Write string to file
local function write_file(path, content)
  local f = io.open(path, "w")
  if not f then
    error("Could not open file for writing: " .. path)
  end
  f:write(content)
  f:close()
  print("Written: " .. path)
end

--- Sorted attribute names with preferred ordering for readability
local function sorted_attr_names(attrs)
  local hardcoded = { fg = "1", bg = "2", sp = "3", blend = "4", link = "0" }
  local sorted = {}
  for attr in pairs(attrs) do
    sorted[#sorted + 1] = attr
  end
  table.sort(sorted, function(a, b)
    return (hardcoded[a] or a) < (hardcoded[b] or b)
  end)
  return sorted
end

--- Safe lua key for group name
local function safe_key(name)
  if name:match("^[%a_][%w_]*$") then
    return name
  else
    return '["' .. name .. '"]'
  end
end

--- Serialize compiled highlights into a lua source file
local function serialize_theme(compiled)
  -- Sort groups alphabetically
  local groups = {}
  for name in pairs(compiled) do
    groups[#groups + 1] = name
  end
  table.sort(groups)

  local lines = {}
  lines[#lines + 1] = "-- This file is auto-generated by build.lua. DO NOT EDIT."
  lines[#lines + 1] = "-- stylua: ignore start"
  lines[#lines + 1] = "return {"

  for _, name in ipairs(groups) do
    local attrs = compiled[name]
    local parts = {}
    for _, attr in ipairs(sorted_attr_names(attrs)) do
      local val = attrs[attr]
      if type(val) == "string" then
        parts[#parts + 1] = string.format('%s = "%s"', attr, val)
      elseif type(val) == "number" then
        parts[#parts + 1] = string.format("%s = %s", attr, tostring(val))
      elseif type(val) == "boolean" then
        parts[#parts + 1] = string.format("%s = %s", attr, tostring(val))
      end
    end
    lines[#lines + 1] = string.format("  %s = { %s },", safe_key(name), table.concat(parts, ", "))
  end

  lines[#lines + 1] = "}"
  lines[#lines + 1] = "-- stylua: ignore end"
  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

--- Extract terminal colors from vim.g
local function extract_terminal_colors()
  local colors = {}
  for i = 0, 15 do
    local key = "terminal_color_" .. i
    if vim.g[key] then
      colors[key] = vim.g[key]
    end
  end
  return colors
end

--- Serialize terminal colors
local function serialize_terminal_colors(colors)
  local lines = {}
  lines[#lines + 1] = "-- This file is auto-generated by build.lua. DO NOT EDIT."
  lines[#lines + 1] = "return {"
  for i = 0, 15 do
    local key = "terminal_color_" .. i
    if colors[key] then
      lines[#lines + 1] = string.format('  ["%s"] = "%s",', key, colors[key])
    end
  end
  lines[#lines + 1] = "}"
  lines[#lines + 1] = ""
  return table.concat(lines, "\n")
end

local compile = require("lush.compiler")

for _, variant in ipairs({ "dark", "light" }) do
  -- Reset state
  vim.o.background = variant
  package.loaded["bluloco"] = nil
  package.loaded["lush_theme.bluloco"] = nil

  -- Setup bluloco config
  local bluloco = require("bluloco")
  bluloco.setup({
    style = variant,
    transparent = false,
    italics = false,
    terminal = true,
    guicursor = false,
    rainbow_headings = false,
  })

  -- Load and compile the lush theme
  local parsed = require("lush_theme.bluloco")
  local compiled = compile(parsed)

  -- Write theme
  write_file(theme_dir .. "/" .. variant .. ".lua", serialize_theme(compiled))

  -- Write terminal colors
  write_file(theme_dir .. "/terminal_" .. variant .. ".lua", serialize_terminal_colors(extract_terminal_colors()))

  -- Cleanup for next iteration
  package.loaded["bluloco"] = nil
  package.loaded["lush_theme.bluloco"] = nil
  for i = 0, 15 do
    vim.g["terminal_color_" .. i] = nil
  end
end

print("Build complete!")
