-- This file is auto-generated by build.lua. DO NOT EDIT.
return {
  ["terminal_color_0"] = "#42444D",
  ["terminal_color_1"] = "#FC2C4F",
  ["terminal_color_2"] = "#25A25B",
  ["terminal_color_3"] = "#FF956B",
  ["terminal_color_4"] = "#3477FE",
  ["terminal_color_5"] = "#A081FE",
  ["terminal_color_6"] = "#4484AB",
  ["terminal_color_7"] = "#CDD3E0",
  ["terminal_color_8"] = "#8F99AE",
  ["terminal_color_9"] = "#FF617E",
  ["terminal_color_10"] = "#3FC669",
  ["terminal_color_11"] = "#F9C958",
  ["terminal_color_12"] = "#10AFFE",
  ["terminal_color_13"] = "#FF7AF8",
  ["terminal_color_14"] = "#5DB8BB",
  ["terminal_color_15"] = "#FFFFFF",
}
