-- This file is auto-generated by build.lua. DO NOT EDIT.
return {
  ["terminal_color_0"] = "#383B42",
  ["terminal_color_1"] = "#D42551",
  ["terminal_color_2"] = "#239549",
  ["terminal_color_3"] = "#DE631B",
  ["terminal_color_4"] = "#255EE4",
  ["terminal_color_5"] = "#813DF0",
  ["terminal_color_6"] = "#26608C",
  ["terminal_color_7"] = "#B9BAC1",
  ["terminal_color_8"] = "#686B78",
  ["terminal_color_9"] = "#FF617E",
  ["terminal_color_10"] = "#3CBE67",
  ["terminal_color_11"] = "#C4A231",
  ["terminal_color_12"] = "#0099E0",
  ["terminal_color_13"] = "#CD32C0",
  ["terminal_color_14"] = "#6D93BA",
  ["terminal_color_15"] = "#D4D4D4",
}
