name: panvimdoc

on:
  push:
    branches: [main]
    paths:
      - README.md

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: generate vimdoc
    steps:
      - uses: actions/checkout@v4
      - name: generate vimdoc
        uses: kdheepak/panvimdoc@v5.0.0
        with:
          vimdoc: bluloco
          description: "A fancy and sophisticated designer neovim theme"
          version: "Neovim"
          demojify: true
          treesitter: true
          ignorerawblocks: true
          shiftheadinglevelby: -1
      - name: add spacing after callouts
        run: perl -0pi -e 's/(^  (?:Notes?|Warning|Deprecated):.*(?:\n  .*)*)\n(?=\S)/$1\n\n/gmi' doc/bluloco.txt
      - name: generate help tags
        run: vim -es -u NONE -c "helptags doc" -c "qa"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(docs): auto generate vimdoc"
